#!/usr/bin/env bash
set -euo pipefail

# scripts/guardrails.sh — repo hygiene checks for CI.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if ! command -v rg >/dev/null 2>&1; then
  echo "error: ripgrep (rg) is required for guardrails" >&2
  exit 2
fi

run_rg() {
  rg --no-heading --line-number --with-filename -S \
    --glob '!scripts/guardrails.sh' \
    --glob '!vendor/**' \
    --glob '!packages/native/vendor/**' \
    --glob '!**/node_modules/**' \
    --glob '!**/dist/**' \
    "$@"
}

has_violations=0

print_section() {
  echo
  echo "== $1 =="
}

check_pattern() {
  local label="$1"
  local pattern="$2"
  shift 2

  print_section "${label}"
  local hits
  hits="$(run_rg "${pattern}" "${repo_root}" || true)"
  if [[ -n "${hits}" ]]; then
    echo "${hits}"
    has_violations=1
  else
    echo "ok"
  fi
}

check_pattern "No legacy package scope" "@zireael-ui/"
check_pattern "No legacy product name form" "\\bZireael\\s+UI\\b"
check_pattern "No TODO/FIXME markers" "\\b(TODO|FIXME)\\b"
check_pattern "No AI-generated markers" "AI-generated"

print_section "Drawlist codegen files present"
for required in \
  "scripts/drawlist-spec.ts" \
  "scripts/generate-drawlist-writers.ts" \
  "packages/core/src/drawlist/writers.gen.ts"; do
  if [[ ! -f "${repo_root}/${required}" ]]; then
    echo "missing required file: ${required}"
    has_violations=1
  fi
done
if [[ "${has_violations}" -eq 0 ]]; then
  echo "ok"
fi

print_section "Drawlist codegen markers wired"
if ! rg -n "^// AUTO-GENERATED by scripts/generate-drawlist-writers.ts" \
  "${repo_root}/packages/core/src/drawlist/writers.gen.ts" >/dev/null 2>&1; then
  echo "missing AUTO-GENERATED marker in packages/core/src/drawlist/writers.gen.ts"
  has_violations=1
fi
if ! rg -n "Source of truth: scripts/drawlist-spec.ts" \
  "${repo_root}/packages/core/src/drawlist/writers.gen.ts" >/dev/null 2>&1; then
  echo "missing source-of-truth marker in packages/core/src/drawlist/writers.gen.ts"
  has_violations=1
fi
if ! rg -n "from \"\\./writers\\.gen\\.js\"" \
  "${repo_root}/packages/core/src/drawlist/builder_v3.ts" >/dev/null 2>&1; then
  echo "builder_v3.ts is not wired to import ./writers.gen.js"
  has_violations=1
fi
if [[ "${has_violations}" -eq 0 ]]; then
  echo "ok"
fi

if [[ "${has_violations}" -ne 0 ]]; then
  echo
  echo "guardrails: FAILED" >&2
  exit 1
fi

echo
echo "guardrails: OK"
