/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DebugStats {
  totalRecords: bigint;
  totalDropped: bigint;
  errorCount: number;
  warnCount: number;
  currentRingUsage: number;
  ringCapacity: number;
}
export interface DebugQueryResult {
  recordsReturned: number;
  recordsAvailable: number;
  oldestRecordId: bigint;
  newestRecordId: bigint;
  recordsDropped: number;
}
export declare function engineDebugEnable(
  engineId: number,
  config?: object | undefined | null,
): number;
export declare function engineDebugDisable(engineId: number): number;
export declare function engineDebugQuery(
  engineId: number,
  query: object | undefined | null,
  outHeaders: Uint8Array,
): DebugQueryResult;
export declare function engineDebugGetPayload(
  engineId: number,
  recordId: bigint,
  outPayload: Uint8Array,
): number;
export declare function engineDebugGetStats(engineId: number): DebugStats;
export declare function engineDebugExport(engineId: number, outBuf: Uint8Array): number;
export declare function engineDebugReset(engineId: number): number;
export interface EngineMetrics {
  structSize: number;
  negotiatedEngineAbiMajor: number;
  negotiatedEngineAbiMinor: number;
  negotiatedEngineAbiPatch: number;
  negotiatedDrawlistVersion: number;
  negotiatedEventBatchVersion: number;
  frameIndex: bigint;
  fps: number;
  bytesEmittedTotal: bigint;
  bytesEmittedLastFrame: number;
  dirtyLinesLastFrame: number;
  dirtyColsLastFrame: number;
  usInputLastFrame: number;
  usDrawlistLastFrame: number;
  usDiffLastFrame: number;
  usWriteLastFrame: number;
  eventsOutLastPoll: number;
  eventsDroppedTotal: number;
  arenaFrameHighWaterBytes: bigint;
  arenaPersistentHighWaterBytes: bigint;
  damageRectsLastFrame: number;
  damageCellsLastFrame: number;
  damageFullFrame: boolean;
}
export interface TerminalCaps {
  /** Color mode: 0=unknown, 1=16, 2=256, 3=rgb */
  colorMode: number;
  supportsMouse: boolean;
  supportsBracketedPaste: boolean;
  supportsFocusEvents: boolean;
  supportsOsc52: boolean;
  supportsSyncUpdate: boolean;
  supportsScrollRegion: boolean;
  supportsCursorShape: boolean;
  supportsOutputWaitWritable: boolean;
  supportsUnderlineStyles: boolean;
  supportsColoredUnderlines: boolean;
  supportsHyperlinks: boolean;
  /** Bitmask of supported SGR attributes */
  sgrAttrsSupported: number;
}
export declare function engineCreate(config?: object | undefined | null): number;
export declare function engineDestroy(engineId: number): void;
export declare function engineSubmitDrawlist(engineId: number, drawlist: Uint8Array): number;
export declare function enginePresent(engineId: number): number;
export declare function enginePollEvents(
  engineId: number,
  timeoutMs: number,
  out: Uint8Array,
): number;
export declare function enginePostUserEvent(
  engineId: number,
  tag: number,
  payload: Uint8Array,
): number;
export declare function engineSetConfig(engineId: number, cfg?: object | undefined | null): number;
export declare function engineGetMetrics(engineId: number): EngineMetrics;
export declare function engineGetCaps(engineId: number): TerminalCaps;
